#!/usr/bin/env python3
"""Generate tests/bootanim/fixture.h: a real BAN1 blob from the Python
encoder (tools/encode_bootanim.py), plus the expected decoded canvas for
each frame, so host_test.c can prove the C decoder agrees with the actual
encoder -- not just a hand-built blob.

Canvas is 21x13 (odd width, not a multiple of typical strip sizes) so the
host test's 64-byte strip buffer is forced to split rows mid-run.

Frames:
  0: noisy field (np.random.default_rng(7))              -- keyframe
  1: same field with a 4x3 block of 0xBEEF at (5,4)       -- delta rect
  2: identical to frame 1                                  -- hold (0 rects)
  3: the 0xBEEF block moved to (9,6)                       -- delta rect(s)

Run: ~/zephyr-v4.4.0/.venv/bin/python3 tests/bootanim/gen_fixture.py
"""
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "tools"))
import encode_bootanim as enc

W, H = 21, 13
FPS = 12
BLOCK_W, BLOCK_H = 4, 3


def make_frames():
    rng = np.random.default_rng(7)
    frame0 = rng.integers(0, 0x10000, (H, W), dtype=np.uint16)

    frame1 = frame0.copy()
    frame1[4:4 + BLOCK_H, 5:5 + BLOCK_W] = 0xBEEF

    frame2 = frame1.copy()  # identical -> must encode as a hold frame

    frame3 = frame0.copy()
    frame3[6:6 + BLOCK_H, 9:9 + BLOCK_W] = 0xBEEF

    return [frame0, frame1, frame2, frame3]


def frame_record(blob, per_frame, idx):
    off = 12 + sum(per_frame[:idx])
    return blob[off:off + per_frame[idx]]


def dump_bytes(name, data, lines, indent="\t"):
    lines.append(f"static const uint8_t {name}[{len(data)}] = {{")
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        lines.append(f"{indent}{chunk},")
    lines.append("};")


def main():
    frames = make_frames()
    blob, per_frame = enc.encode(frames, FPS, big_endian=True)

    # Frame 2 is identical to frame 1: must encode as a hold frame, i.e. a
    # bare rect_count=0 byte and nothing else.
    hold_record = frame_record(blob, per_frame, 2)
    assert hold_record == b"\x00", (
        f"expected frame 2 to be a hold frame (b'\\x00'), got {hold_record!r}")

    # Round-trip sanity: the encoder's own decoder must reproduce the frames.
    dec_frames, fps = enc.decode(blob)
    assert fps == FPS
    for a, b in zip(dec_frames, frames):
        assert (a == b).all()

    out_path = Path(__file__).resolve().parent / "fixture.h"
    regen_cmd = "~/zephyr-v4.4.0/.venv/bin/python3 tests/bootanim/gen_fixture.py"

    lines = [
        "/* Generated by tests/bootanim/gen_fixture.py -- do not edit.",
        f" * Regenerate with: {regen_cmd}",
        f" * {W}x{H} canvas, {len(frames)} frames @ {FPS} fps; blob "
        f"{len(blob)} bytes. Cross-checks the C decoder against a blob",
        " * produced by the real Python encoder (tools/encode_bootanim.py).",
        " */",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]
    dump_bytes("fixture_blob", blob, lines)
    lines.append("")

    canvas_bytes = H * W * 2
    lines.append(
        f"static const uint8_t fixture_expect[{len(frames)}][{canvas_bytes}] = {{")
    for frame in frames:
        be_bytes = frame.astype(">u2").tobytes()
        lines.append("\t{")
        for i in range(0, len(be_bytes), 16):
            chunk = ", ".join(f"0x{b:02x}" for b in be_bytes[i:i + 16])
            lines.append(f"\t\t{chunk},")
        lines.append("\t},")
    lines.append("};")
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"fixture: {out_path} ({len(blob)}-byte blob, "
          f"{len(frames)} x {canvas_bytes}-byte expected canvases)")


if __name__ == "__main__":
    main()
