/* Standalone host test for bootanim_dec (macOS-friendly; native_sim is
 * Linux-only).
 * Build & run:
 *   cc -I ../../firmware/src host_test.c ../../firmware/src/bootanim_dec.c \
 *      -o /tmp/batest && /tmp/batest
 */
#include <stdio.h>
#include <string.h>
#include "bootanim_dec.h"
#include "fixture.h"

static int failures;
#define CHECK(c, m) do { if (!(c)) { printf("FAIL: %s\n", m); failures++; } \
	else { printf("PASS: %s\n", m); } } while (0)

/* Hand-built BAN1 blob per the format documented in
 * tools/encode_bootanim.py: 4x3 canvas, 12 fps, 2 frames.
 * Frame 0: one full-canvas rect, a single RLE run of 12 x 0xBEEF
 *          (ctrl 0x8A = run of 12).
 * Frame 1: one 2x1 rect at (1,1), two literal pixels 0x1234 0x5678
 *          (ctrl 0x01 = 2 literals). */
static const uint8_t blob[] = {
	'B', 'A', 'N', '1', 4, 0, 3, 0, 12, 1, 2, 0,
	/* frame 0 */ 1,
	0, 0, 0, 0, 4, 0, 3, 0, 3, 0, 0, 0,
	0x8a, 0xbe, 0xef,
	/* frame 1 */ 1,
	1, 0, 1, 0, 2, 0, 1, 0, 5, 0, 0, 0,
	0x01, 0x12, 0x34, 0x56, 0x78,
};

/* Payload shorter than the rect's pixel count: a run of 7 cannot fill a
 * 12-pixel rect; the decoder must hit the payload end and fail, not
 * overread past it. */
static const uint8_t short_run[] = {
	'B', 'A', 'N', '1', 4, 0, 3, 0, 12, 1, 1, 0,
	1,
	0, 0, 0, 0, 4, 0, 3, 0, 3, 0, 0, 0,
	0x85, 0xbe, 0xef,	/* run of 7, rect needs 12 */
};

/* Literal op promises 12 pixels but the payload holds only one. */
static const uint8_t short_lit[] = {
	'B', 'A', 'N', '1', 4, 0, 3, 0, 12, 1, 1, 0,
	1,
	0, 0, 0, 0, 4, 0, 3, 0, 3, 0, 0, 0,
	0x0b, 0x12, 0x34,	/* ctrl says 12 literals, 1 present */
};

static uint8_t canvas[3][4][2];
static int blits;

/* Cross-language fixture: fixture.h (generated by gen_fixture.py) holds a
 * BAN1 blob produced by the real Python encoder plus each frame's expected
 * canvas, so the C decoder is proven against the actual encoder output, not
 * just a hand-built blob. */
static uint8_t fx_canvas[13][21][2];

static void fx_blit(uint16_t x, uint16_t y, uint16_t w, uint16_t h,
		    const uint8_t *pix, void *user)
{
	(void)user;
	for (uint16_t r = 0; r < h; r++)
		memcpy(&fx_canvas[y + r][x][0], pix + (size_t)r * w * 2,
		       (size_t)w * 2);
}

static void blit(uint16_t x, uint16_t y, uint16_t w, uint16_t h,
		 const uint8_t *pix, void *user)
{
	(void)user;
	blits++;
	for (uint16_t r = 0; r < h; r++)
		memcpy(&canvas[y + r][x][0], pix + (size_t)r * w * 2,
		       (size_t)w * 2);
}

int main(void)
{
	struct ba_header hdr;
	size_t off;

	CHECK(ba_parse_header(blob, sizeof(blob), &hdr, &off), "header parses");
	CHECK(hdr.w == 4 && hdr.h == 3, "dimensions 4x3");
	CHECK(hdr.fps == 12 && hdr.nframes == 2, "fps and frame count");
	CHECK(off == 12, "header is 12 bytes");
	CHECK(!ba_parse_header((const uint8_t *)"nope", 4, &hdr, &off),
	      "bad magic rejected");

	/* A strip of 4 pixels forces frame 0 (12 px) through three blits,
	 * so the single RLE run must survive strip boundaries. */
	uint8_t strip[8];

	CHECK(ba_decode_frame(blob, sizeof(blob), &off, strip, sizeof(strip),
			      blit, NULL) == 1, "frame 0 decodes, 1 rect");
	CHECK(blits == 3, "frame 0 split into 3 strips");
	CHECK(canvas[0][0][0] == 0xbe && canvas[0][0][1] == 0xef &&
	      canvas[2][3][0] == 0xbe && canvas[2][3][1] == 0xef,
	      "run fills first and last pixel");

	CHECK(ba_decode_frame(blob, sizeof(blob), &off, strip, sizeof(strip),
			      blit, NULL) == 1, "frame 1 decodes, 1 rect");
	CHECK(canvas[1][1][0] == 0x12 && canvas[1][1][1] == 0x34 &&
	      canvas[1][2][0] == 0x56 && canvas[1][2][1] == 0x78,
	      "literal pixels land at (1,1)-(2,1)");
	CHECK(canvas[1][0][0] == 0xbe, "untouched pixel keeps frame 0 value");
	CHECK(off == sizeof(blob), "offset lands at end of blob");

	/* Truncation must fail cleanly, never overread. */
	off = 12;
	CHECK(ba_decode_frame(blob, 20, &off, strip, sizeof(strip),
			      blit, NULL) == -1, "truncated blob -> -1");

	off = 12;
	CHECK(ba_decode_frame(short_run, sizeof(short_run), &off, strip,
			      sizeof(strip), blit, NULL) == -1,
	      "run underruns rect pixel count -> -1");
	off = 12;
	CHECK(ba_decode_frame(short_lit, sizeof(short_lit), &off, strip,
			      sizeof(strip), blit, NULL) == -1,
	      "literals underrun rect pixel count -> -1");

	/* Cross-language fixture: decode a blob produced by the real Python
	 * encoder and compare every frame against its expected canvas. A
	 * 64-byte strip on a 21-wide canvas gives 64 / (2*21) = 1 row per
	 * strip, forcing PackBits16 runs to carry over strip boundaries
	 * mid-run. */
	struct ba_header fx_hdr;
	size_t fx_off;

	CHECK(ba_parse_header(fixture_blob, sizeof(fixture_blob), &fx_hdr,
			      &fx_off), "fixture header parses");
	CHECK(fx_hdr.w == 21 && fx_hdr.h == 13, "fixture dimensions 21x13");
	CHECK(fx_hdr.nframes == 4, "fixture has 4 frames");

	uint8_t fx_strip[64];

	for (int i = 0; i < fx_hdr.nframes; i++) {
		int rects = ba_decode_frame(fixture_blob, sizeof(fixture_blob),
					    &fx_off, fx_strip, sizeof(fx_strip),
					    fx_blit, NULL);
		char msg[80];

		snprintf(msg, sizeof(msg), "fixture frame %d decodes", i);
		CHECK(rects >= 0, msg);

		snprintf(msg, sizeof(msg),
			"fixture frame %d matches expected canvas", i);
		CHECK(memcmp(fx_canvas, fixture_expect[i], sizeof(fx_canvas)) == 0,
		      msg);

		if (i == 2)
			CHECK(rects == 0, "fixture frame 2 is a hold frame (0 rects)");
	}
	CHECK(fx_off == sizeof(fixture_blob),
	      "fixture offset lands at end of fixture_blob");

	printf("%s\n", failures ? "FAILURES" : "all ok");
	return failures != 0;
}
