#!/usr/bin/env python3
"""Rasterise design/dial_face.py into firmware/src/dial_gen.h.

    python3 tools/encode_dial.py

One static face (RGB565, no alpha - its corners are COL_BG so it blends into
the screen and costs no per-pixel blend), and six needles: long and short,
each in the three severity colours. Three bitmaps rather than one recoloured
at runtime, because recolour and rotation on the same object is two transforms
per redraw on a chip that already takes 63 ms to push a frame.

BYTE ORDER: LITTLE-endian, and that is NOT what CONFIG_LV_COLOR_16_SWAP=y
would suggest. Measured on hardware 2026-09-23: emitting big-endian to match
the swap rendered the face's 0x0E1116 background as (128,64,64), a flat
salmon, which is exactly what 0x0882 reads as with its bytes exchanged.

The swap setting describes the DISPLAY BUFFER - how LVGL hands finished
pixels to the ILI9341 - and the driver applies it on the way out. Image
descriptors are read before that point, in the CPU's own order. --swap is
kept only so the next person can reproduce the wrong answer in one command
rather than re-deriving it.
"""
import argparse, os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "design"))
from dial_face import render_face, render_needle, SEVERITY, R, FACE_PX, REDLINE, SWEEP0, SWEEP

AP = argparse.ArgumentParser()
AP.add_argument("--out", default="firmware/src/dial_gen.h")
AP.add_argument("--swap", action="store_true",
                help="big-endian RGB565; wrong on this hardware, see the note")
A = AP.parse_args()

def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def pack(im, alpha):
    px = im.convert("RGBA").load()
    w, h = im.size
    rgb, al = bytearray(), bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            v = rgb565(r, g, b)
            rgb += bytes((v >> 8, v & 0xFF)) if A.swap else bytes((v & 0xFF, v >> 8))
            al.append(a)
    return bytes(rgb) + (bytes(al) if alpha else b""), w, h

def carray(name, data):
    out = ['/* 64, not LV_ATTRIBUTE_MEM_ALIGN: that macro is defined EMPTY by',
           ' * default (lv_conf_template.h:550) and expanded to nothing, so the',
           ' * arrays stayed byte-aligned and lv_draw_buf_init warned once per',
           ' * draw. LV_DRAW_BUF_ALIGN is 4 here; 64 covers any value it could',
           ' * take and costs at most 63 bytes of padding. */',
           "static const uint8_t %s[] __attribute__((aligned(64))) = {" % name]
    for i in range(0, len(data), 16):
        out.append("\t" + " ".join("0x%02x," % b for b in data[i:i+16]))
    out.append("};")
    return "\n".join(out)

def dsc(name, w, h, alpha):
    cf = "LV_COLOR_FORMAT_RGB565A8" if alpha else "LV_COLOR_FORMAT_RGB565"
    return "\n".join([
        "static const lv_image_dsc_t %s = {" % name,
        "\t.header = { .magic = LV_IMAGE_HEADER_MAGIC,",
        "\t            .cf = %s," % cf,
        "\t            .w = %d, .h = %d, .stride = %d }," % (w, h, w * 2),
        "\t.data_size = sizeof(%s_map)," % name,
        "\t.data = %s_map," % name,
        "};"])

face, r_dot, ir = render_face()
blobs, total = [], 0

fb, fw, fh = pack(face, alpha=False)
blobs.append(("dial_face", fb, fw, fh, False)); total += len(fb)

LONG  = (int(ir) - 6, 3, 15)
SHORT = (int(r_dot) - 4, 2, 10)
pivots = {}
for tag, (ln, hw, tl) in (("long", LONG), ("short", SHORT)):
    for sev, col in SEVERITY.items():
        im, pxv, pyv = render_needle(ln, hw, tl, col)
        b, w, h = pack(im, alpha=True)
        blobs.append(("needle_%s_%s" % (tag, sev), b, w, h, True)); total += len(b)
        pivots[tag] = (pxv, pyv)

H = ["/* Generated by tools/encode_dial.py -- do not edit.",
     " * Artwork lives in design/dial_face.py; the mockup renders the same",
     " * functions, so the picture and the panel cannot drift.",
     " *",
     " * %d bitmaps, %d bytes of flash (%.1f KB)." % (len(blobs), total, total / 1024),
     " * Byte order is %s-endian RGB565 (CONFIG_LV_COLOR_16_SWAP=%s)." %
     ("big" if A.swap else "little", "irrelevant to image data"),
     " */", "#pragma once", "#include <lvgl.h>", "#include <stdint.h>", "",
     "/* Geometry the firmware needs, so it is never written down twice. */",
     "#define DIAL_PX        %d" % FACE_PX,
     "#define DIAL_SWEEP0    %d      /* degrees at 0%%  */" % SWEEP0,
     "#define DIAL_SWEEP     %d      /* degrees of travel */" % SWEEP,
     "#define DIAL_REDLINE   %d" % REDLINE,
     "#define NEEDLE_LONG_PIVOT_X   %d" % pivots["long"][0],
     "#define NEEDLE_LONG_PIVOT_Y   %d" % pivots["long"][1],
     "#define NEEDLE_SHORT_PIVOT_X  %d" % pivots["short"][0],
     "#define NEEDLE_SHORT_PIVOT_Y  %d" % pivots["short"][1],
     ""]
for name, blob, w, h, alpha in blobs:
    H.append(carray(name + "_map", blob)); H.append("")
    H.append(dsc(name, w, h, alpha)); H.append("")

os.makedirs(os.path.dirname(A.out), exist_ok=True)
open(A.out, "w").write("\n".join(H))
print("wrote %s: %d bitmaps, %d bytes (%.1f KB)" % (A.out, len(blobs), total, total / 1024))
for n, b, w, h, al in blobs:
    print("   %-22s %3dx%-3d %s %6d B" % (n, w, h, "RGB565A8" if al else "RGB565  ", len(b)))
