#!/usr/bin/env python3
"""PNG app icons -> firmware/src/icons_gen.h, as LVGL image descriptors.

    python3 tools/encode_icons.py --in reveal/icons --size 40

Why compiled in rather than flashed to a partition like the company logo:
the logo is per-unit and written at the factory, so it has to be data. These
are the same on every unit, they are 29 KB, and flash is the one resource
this board has spare. A partition would buy a write path nobody needs and a
CRC nobody would check.

RGB565A8, not RGB565: the icons have rounded corners and the tile behind them
changes colour with state (panel / amber / green), so they have to composite
rather than be pre-flattened onto one background.

BYTE ORDER: LITTLE-endian, and NOT what CONFIG_LV_COLOR_16_SWAP=y suggests.
Measured on hardware 2026-09-23 with the dial artwork: emitting big-endian to
match the swap rendered 0x0E1116 as a flat salmon. The swap setting describes
the DISPLAY BUFFER - how LVGL hands finished pixels to the ILI9341 - and the
driver applies it on the way out. Image descriptors are read before that, in
the CPU's own order.

ALIGNMENT: explicit. LV_ATTRIBUTE_MEM_ALIGN is defined EMPTY by LVGL's own
default config, so using it does nothing and lv_draw_buf_init warns once per
draw, forever, down the same UART the daemon's protocol shares.
"""
import argparse, os, sys
from PIL import Image

AP = argparse.ArgumentParser()
AP.add_argument("--in", dest="src", default="reveal/icons")
AP.add_argument("--out", default="firmware/src/icons_gen.h")
AP.add_argument("--size", type=int, default=40)
AP.add_argument("--swap", action="store_true",
                help="big-endian; wrong on this hardware, kept to reproduce it")
A = AP.parse_args()

KEYS = ["claude", "illustrator", "photoshop", "spotify", "brave", "pcsx2"]

def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

out, total = [], 0
blobs = []
for key in KEYS:
    p = os.path.join(A.src, key + ".png")
    if not os.path.isfile(p):
        sys.exit("missing icon: %s" % p)
    im = Image.open(p).convert("RGBA").resize((A.size, A.size), Image.LANCZOS)
    px = im.load()
    rgb, alpha = bytearray(), bytearray()
    for y in range(A.size):
        for x in range(A.size):
            r, g, b, a = px[x, y]
            v = rgb565(r, g, b)
            if A.swap:
                rgb += bytes((v >> 8, v & 0xFF))
            else:
                rgb += bytes((v & 0xFF, v >> 8))
            alpha.append(a)
    blob = bytes(rgb) + bytes(alpha)
    blobs.append((key, blob))
    total += len(blob)

def carray(name, data):
    lines = ["static const uint8_t %s[] __attribute__((aligned(64))) = {" % name]
    for i in range(0, len(data), 16):
        lines.append("\t" + " ".join("0x%02x," % b for b in data[i:i+16]))
    lines.append("};")
    return "\n".join(lines)

H = ['/* Generated by tools/encode_icons.py -- do not edit.',
     ' *',
     ' *   python3 tools/encode_icons.py --in %s --size %d%s' %
     (A.src, A.size, " --swap" if A.swap else ""),
     ' *',
     ' * %d icons at %dx%d, RGB565A8, %d bytes of flash.' %
     (len(blobs), A.size, A.size, total),
     ' * Byte order is %s-endian RGB565, matching CONFIG_LV_COLOR_16_SWAP=%s.' %
     ("big" if A.swap else "little", "irrelevant to image data"),
     ' */',
     '#pragma once',
     '#include <lvgl.h>',
     '#include <stdint.h>',
     '',
     '#define ICON_PX %d' % A.size,
     '']
for key, blob in blobs:
    H.append(carray("icon_%s_map" % key, blob))
    H.append("")
    H.append("static const lv_image_dsc_t icon_%s = {" % key)
    H.append("\t.header = { .magic = LV_IMAGE_HEADER_MAGIC,")
    H.append("\t            .cf = LV_COLOR_FORMAT_RGB565A8,")
    H.append("\t            .w = %d, .h = %d, .stride = %d }," % (A.size, A.size, A.size*2))
    H.append("\t.data_size = sizeof(icon_%s_map)," % key)
    H.append("\t.data = icon_%s_map," % key)
    H.append("};")
    H.append("")

H.append("/* Key -> icon. The daemon sends the KEY, not a filename: the board")
H.append(" * owns what it can draw, and a key it does not know falls back to")
H.append(" * being drawn as text, which is what makes a custom app still work. */")
H.append("struct icon_entry { const char *key; const lv_image_dsc_t *dsc; };")
H.append("static const struct icon_entry icon_table[] = {")
for key, _ in blobs:
    H.append('\t{ "%s", &icon_%s },' % (key, key))
H.append("};")
H.append("#define ICON_TABLE_N %d" % len(blobs))
H.append("")

os.makedirs(os.path.dirname(A.out), exist_ok=True)
open(A.out, "w").write("\n".join(H))
print("wrote %s: %d icons, %d bytes of flash (%.1f KB)" %
      (A.out, len(blobs), total, total/1024))
